mother(padme, luke).
mother(padme, leia).
father(anakin, luke).
father(anakin, leia).

parent(X, Y) :- mother(X, Y).
parent(X, Y) :- father(X, Y).

sibling(X, Y) :- parent(P, X), parent(P, Y).

alias(anakin, vader).
alias(X, Y) :- aliax(Y, X).

father(X, Y) :- father(Z, Y), alias(Z, X).

kissed(anakin, padme).
kissed(leia, han).
kissed(luke, leia).
kissed(X, Y) :- kissed(Y, X).
kissed(X, Y) :- kissed(X, Z), alias(Z, Y).

gross(X, Y) :- kissed(X, Y), sibling(X, Y).
